# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'activesupport'
gem 'capybara'
gem 'factory_bot'
gem 'httparty'
gem 'pry'
gem 'require_all'
gem 'rspec'
gem 'selenium-webdriver'
gem 'settingslogic'
gem 'site_prism'
